[package]
name = "pixel_game"
version = "0.1.0"
authors = ["valflrt"]
edition = "2021"

[dependencies]
image = { version = "0.24.6", default-features = false, features = ["png"] }


[workspace]
members = ["examples/*"]
